### ISSUE TITLE
How to preserve commits at the destination?

### ISSUE THREAD

**Issue by scriptnull** [google/copybara#143]
Hi, I am trying to replicate commits from a public (external) github repo's PR to private (internal) github repo's PR.

![image](https://user-images.githubusercontent.com/4211715/97666424-ab3fab00-1aa3-11eb-8749-8f0eb79a90b8.png)

As you could notice, I am losing a commit made at the internal PR when we update the external PR. I would like to know if there is a way to preserve it.

For more context, here is my copy.bara.sky file:
```
core.workflow(
    name = "default",
    origin = git.github_pr_origin(
      url = "git@github.com:sample-organisation/external.git",
    ),

    destination = git.github_pr_destination(
      url = "git@github.com:sample-organisation/internal.git",
      destination_ref = "main",
      pr_branch = "from_external_${CONTEXT_REFERENCE}",
      title = "pr from external ${CONTEXT_REFERENCE} ",
      body = "this is a sample pull request",
      integrates = [],
    ),

    mode = "CHANGE_REQUEST",
    
    set_rev_id = False,

    origin_files = glob(["external/**"]),
    
    destination_files = glob(["external/**"]),

    authoring = authoring.pass_thru("Example <example@example.com>"),
    transformations = [
        metadata.restore_author("ORIGINAL_AUTHOR", search_all_changes = True),
        metadata.expose_label("COPYBARA_INTEGRATE_REVIEW"),
    ],
)
```
I thought `COPYBARA_INTEGRATE_REVIEW` and `integrates = [],` could help me achieve this based on the conversation at https://github.com/google/copybara/issues/140 and in various other github issues in the copybara repo.

But I guess I am genuinely not able to understand how these two work. It would be of much help if someone could explain them to me and if they make sense for what I am trying to achieve.

**Comment by mikelalcon** [comment]
Yeah, each external -> import will overwrite the history for the internal PR. This is not generally a problem for us as we either:

         1) Ask the external user to fix the PR (commit 3).
         2) Take ownership of the internal PR, make it work (commit 2) and submit.

When we need both, we usually rely on 1) or 2), or doing 1) first and then 2) (make it work for our internal system).

**Comment by mikelalcon** [comment]
Integrate usage is more for this scenario:

1) external PR containing "external only files" and files we have internally too. Can contain multiple commits from different authors.
2) We import all the changes with CHANGE_REQUEST. This is similar to SQUASH (squashes with baseline)
3) Once submitted internally, it is exported with internal only changes to the external repo. Generally using ITERATIVE
4) If label COPYBARA_INTEGRATE_REVIEW is present for each of the internal commits, we will create a fake-merge with the external PR. That means that we can "attribute" the external PR changes, even if multiple authors, since it shows as merge. In addition to that, if the external PR has changes to external only files, we will put those files in the final merge commit (IOW it is not a fake-merge but a semi fake-merge).

Hope it helps.
