### ISSUE TITLE
Can anyone please help with core.feedback config example?

### ISSUE THREAD

**Issue by vivek21ladke** [google/copybara#169]
I want to mirror comments and labels from a external change after_migration, but not unable to understand what params needed in actions in following config.  

core.feedback(
    name = "getMetaData",
    origin = git.gerrit_trigger("ssh://server:repo.git", checker=None),
    destination = git.gerrit_api(url='https://server/change/number', checker=None),
    actions=[ ????
        ],
    description=None)

Could you please help with core.feeback config with example?

**Comment by mikelalcon** [comment]
Feedback has two flavors:

           

- `after_migration`/`after_all_migration`: This one acts as a hook that is executed after a migration happen. It can be used to opportunistically migrate other state than files (like comments, etc.). But only will be run when a code migration happen. The other usage is to update state in the origin and/or destination about that migration (Doing a +1 in the origin, a comment in the GH PR, etc.)

-  `core.feedback`: An different workflow that can be triggered independently of any `core.workflow`. Can be used to sync state between systems. We also use them to asynchronously post back CI results back to the origin. Can also be used to more comments as they happen. The main problem is that you need some sort of watcher of events that we currently don't have it OSS (It is too coupled with our internal systems). We would love at some point to have something in this area.

Example of `after_migration`:
```
# Type for ctx is feedback.finish_hook_context
def do_foo(ctx):
   ctx.console.info("Hello this is after migration hook!")
   for effect in ctx.effects:
          if effect.type == "CREATED" or effect.type == "UPDATED":
               created_ref = effect.destination_ref.id
               type = effect.destination_ref.type   
               # use those fields
   # ctx.destination is of type https://github.com/google/copybara/blob/master/docs/reference.md#github_api_obj
   # any method should work. Same for ctx.origin
core.workflow(
   name = "aaa",
   origin =...,
   destination = git.github_destination(...),
   ...  
   after_migration = [do_foo]
)
```

`core.feedback` is similar. A equivalent Gerrit to gerrit core.feedback that receives gerrit changes would be:

```
# type of ctx is feedback.context
def do_foo2(ctx):
    # Each element in refs is the parameters passed in the CLI (Excluding workflow name, config, flags, etc.)
     for ref in ctx.refs:
                   ctx.console.info("Param: " + ref) 
     ctx.origin.... # same as the after_migration ones
     ctx.destination.... # same as the after_migration ones

   
 core.feedback (
      name = "foo",
      origin = git.gerrit_trigger(url),
      destination = git.gerrit_api(another_url), # another_url could be 'url' if acting on the same repo
      actions = [do_foo2],
)
```

It is going to be tricky to use them in without watchers, etc. But we are definitely interested on how this turns out. Please keep us posted :)  and feel free to send us contributions.

**Comment by vivek21ladke** [comment]
I want run after_migration for CHANGE_REQUEST mode to copy comments. As per doc after_migration not mentioned for CHANGE_REQUEST mode.
Can you help with sample config with after_migration?

**Comment by mikelalcon** [comment]
`after_migration` should work if the change is not a noop and `after_workflow` should trigger always.

**Comment by vivek21ladke** [comment]
Hi Mikel,
It would be great help if you could you please help with sample format mirroring comments for after_migration? If hard to figure out what type of param needed for ctx.origin/ctx.destination? How can i debug this, like printing object to check, what they have? ex. ctx.effects. I m newbie here.
