### ISSUE TITLE
Using copybara for dynamically  generated files

### ISSUE THREAD

**Issue by ainskeep** [google/copybara#193]
I'm looking for advice on how to handle the use case below:

My origin repo repo dynamically generates files that I want to copy to my destination repo. I've run into two issues with this so far

1. Copybara needs a git reference, so files that are generated and not checked in cannot be targeted. I can workaround this by checking them in locally and referencing the local repo as my origin. (We would prefer these files not be checked into the origin repo)

2.  The URL for the origin repo cannot be passed in by a flag, or be a relative path. This stops me from using a local repo in CI since working directories in CI are often unique to the run. If Copybara could handle environment variables, take a flag for origin URL or use relative paths for local repos, I could work around this.

Any feedback on approach is appreciated

**Comment by mikelalcon** [comment]
For 1. you might be able to use a undocumented flag that allows to run a
tool after checkout (
https://github.com/google/copybara/blob/master/java/com/google/copybara/git/GitOriginOptions.java#L34).
We don't recommend it in general, but might help you.

Another undocummented feature is that you can use "repo_url ref" as
reference instead of "ref" to fetch from another repo. Eg.
copybara path/to/copy.bara.sky workflow_name "https://github.com/some/repo
main"

**Comment by ainskeep** [comment]
The second option of passing in the repo_url_ref as an argument is working for my use case. Thanks for the suggestion!
