### ISSUE TITLE
Is there a way for Copybara to include tag from source repo into a destination commit?

### ISSUE THREAD

**Issue by georgique** [google/copybara#240]
Idea behind this is to trigger Copybara when a release is made in source repo. Release would include a tag.
Would like Copybara to get that tag and push it to the destination repos too.

I see that there is tag_name in git.destination, but I'm not sure how to make Copybara retrieve tag from the source repo.

**Comment by jordanlin00** [comment]
If this is just mirroring, you can use [git.mirror](https://github.com/google/copybara/blob/master/docs/reference.md#gitmirror) with tag refs namespace

**Comment by hsudhof** [comment]
git_tag takes a label template. Copybara provides a wide array for labels, in particular you can use "${COPYBARA_CONTEXT_REFERENCE}" for the version that copybara was passed as a ref. If you use a version_selector, this will be the tag. 
Otherwise, if this is in an iterative settings, you can use the various describe labels on GitRevision to find it.

**Comment by georgique** [comment]
Got it, thanks
