### ISSUE TITLE
How to overlay a file such as README.md

### ISSUE THREAD

**Issue by DarthHater** [google/copybara#43]
Hi there Copybara friends!

I'm working on another project using this fabulous tool, and I was wondering about a particular use case and how to best accomplish it.

```
core.workflow(
    name = "default",
    origin = git.origin(
        url = sourceUrl,
        ref = "master",
    ),
    destination = git.destination(
        url = destinationUrl,
        fetch = "master",
        push = "master",
    ),
    mode = "ITERATIVE",
    # Change path to the folder you want to publish publicly
    origin_files = glob(["**"], exclude = ["copy.bara.sky", ".copybara/**", "Jenkinsfile", "README.md"]),
    destination_files = glob(["**"]),

    authoring = authoring.pass_thru("THIS GUY <dude@email.com>"),
    transformations = [
      metadata.squash_notes(prefix = 'Public export of code:\n\n', show_description = False),
      core.copy(".copybara/public", "", paths = glob(["README.md"]))
    ],
)
```

I was wondering if this is the best way to accomplish overlaying a public README.md from an internal repo. I'm asking this publicly because I'm not 100% sure how to dry run the copybara stuff and see what a public repo will look like, and as well to just see if there is a better way to accomplish this. I think the core.replace stuff is a bit too granular, in this case replacing the file completely seems to make the most sense.

Thanks!

**Comment by mikelalcon** [comment]
Hi!

K, IIUC you have a `.copybara/public/README.md` that you want to include despite excluding`.copybara`. You can do that by doing :

```
 origin_files = glob(["**"], exclude = ["copy.bara.sky", ".copybara/**", "Jenkinsfile", "README.md"]) + glob([".copybara/public/README.md"]),
```

Glob can be added. And the semantic is 'OR'. So this would exclude all `.copybara` files except `.copybara/public/README.md`.

The second thing you would do is:
```
core.move(".copybara/public/README.md", "README.md"))
```
Note that this transformation is reversible. A good property to have for accepting ` CHANGE_REQUEST` contributions from the public repo.

Last thing, about testing it locally :) 

This is how I usually test things locally. I found it to be the most convenient way (because you can use a non bare repo):

```
rm -rf /tmp/local_repo; copybara foo/copy.bara.sky workflow --dry-run --git-destination-path /tmp/local_repo
```

Then /tmp/local_repo is a non-bare repo with remote origin set to the remote repo and with the created commits in the checked in branch.

**Comment by DarthHater** [comment]
That's about what I was looking for! Thanks for the explanation, I'll give it a go.

**Comment by mikelalcon** [comment]
Great! feel free to reopen if it doesn't work.

**Comment by DarthHater** [comment]
This worked fairly well! However, if the file doesn't exist in the early commits of the project, it'll barf. What I ended up doing was running it without this config until we'd migrated out everything sans the internal file, and then modified it to do the move of the file.

**Comment by mikelalcon** [comment]
Another option is to wrap core.move in https://github.com/google/copybara/blob/master/docs/reference.md#core.transform

and set ignore_noop = True. 

note that this should be temporary since we don't recommend permanent ignore_noops.

**Comment by jdillon** [comment]
BTW, looks like for an initial migrate with transformations with `core.move` where early revisions do not have this, can also be done with cli option `--ignore-noop` to limit the noop handling just for that first `--init-history` migration.
