### ISSUE TITLE
ITERATIVE workflow overrides changes, CHANGE_REQUEST workflow only succeeded for a first change

### ISSUE THREAD

**Issue by alshan** [google/copybara#77]
Hi, I'm experimenting with git-to-git export-import scenario.
For exporting from private repo to public repo I'm using ITERATIVE workflow with git.github_origin and git.github_destination.
And for importing form public repo to private repo I'm using CHANGE_REQUEST workflow with git.github_origin and git.github_pr_destination.

This setup does work for me in some cases, however in some other cases it doesn't. 

Issue 1
When running ITERATIVE workflow (exporting priv-->pub), copybara replaces all files changed in the destination with their earlier revisions existing in the origin. Copybara probably fails to find the baseline commit in this scenario but I don't see any errors or warnings. 

Issue 2
When running CHANGE_REQUEST workflow (importing priv<--pub) it works perfect for a first change but fails for subsequent change.
Consider the following scenario:
1. in the dest repo add 'line 1' to dest.txt file.
2. run copybara import --> PR in the origin githab repo is created.
3. accept the PR (merge or rebase - it doesn't matter), delete the branch
4. optionally (the entire scenario fails either way) run copybara export --> "Iterative workflow produced no changes in the destination for resolved ref: 1234"
5. in the dest repo add 'line 2' to dest.txt file.
6. run copybara import --> `ERROR: Conflict detected while rebasing <usr>/copybara/temp/workdir2115951859017918467/checkout to 1234.`

Checking the failed patch at `<usr>/copybara/cache/git_repos/<repo url>/rebase-apply/patch`
reveals that it contains additions for both 'line 1' and 'line 2' to dest.txt file.

The only fix I've found for this condition is to remove the patch and run copybara export. This time change '1234' (the first one) would pass through and be pushed to the dest. But this will effectively destroy all the recent changes in the dest ('line 2' in our case) - see Issue 1.

Are these issues really a bugs or desired behavior? 
Is there anything I can try to work around at least one of those?
Thank you.

**Comment by mikelalcon** [comment]
Before entering into detail, one thing to take into account is that Copybara only supports one Source of Truth for some set of files. I am saying that because the problems you are seeing might be related to that.

In particular, git.github_origin and git.github_pr_destination CHANGE_REQUEST seems to be wrong. Given that CHANGE_REQUEST should be used from non-sot, I would expect git.github_pr_origin and not git.github_origin (Destination is fine). The other thing is that Copybara needs to migrate first from private -> public so that any baseline from a public PR is a valid exported change from private.

Issue 1:
Do you have a repro case of this? Copybara will not migrate if it cannot find the baseline. Unless you use --force.

Issue 2:
I suspect this is a two SoT issue. To make it clear, the correct way of using is that you create a PR in the public repo and don't merge but import to the private one and merge there.

**Comment by alshan** [comment]
Importing public PRs via git.github_pr_origin works perfectly! (Issue2)

**Comment by alshan** [comment]
@mikelalcon here is very simple scenario reproducing 'Issue 1':
- have an 'orig' git repo with file 'a.txt' and a bare 'dest' git repo
- migrate orig-> dest using SQUASH and --force
- clone 'dest' repo and edit a.txt file, then commit & push
- add another file 'b.txt' to 'orig' repo
- migrate orig-> dest using ITERATIVE (no --force)
- pull changes from 'dest' - the result is two empty files: a.txt b.txt 
I.e. changes in a.txt were lost.

log (on the dest side):

```
aceec58 (HEAD -> master, origin/master, origin/HEAD) add b
03719d5 edit dest
3dace90 Project import generated by Copybara.

``` 
git diff HEAD~1:

```
diff --git a/a.txt b/a.txt
index 4b54f7b..e69de29 100644
--- a/a.txt
+++ b/a.txt
@@ -1,2 +0,0 @@
-edited (dest)
-
diff --git a/b.txt b/b.txt
new file mode 100644
index 0000000..e69de29

```

**Comment by alshan** [comment]
Got it, thanx!

**Comment by mikelalcon** [comment]
no problem. Let us know your experience with Copybara! :)
